# bitti
f = open("access.log", "r")
counterUniqueIp=0
listForProxyIp=[]
setForUniqueDomain= set()


try:
    for i in (f):
# part 1:
        part=i.split()
        if(part[3]=="CONNECT" and part[1] not in listForProxyIp):
            counterUniqueIp+=1
            listForProxyIp.append(part[1])
# u can also do this task using set. 
# part 2:
        if(part[3]=="GET"):
            hisseForDomain=part[2].split(":")
            setForUniqueDomain.add(hisseForDomain[0])
# part 3:
    yeniqounter=0       
    counterForThirdQuestion=[0] * len(setForUniqueDomain)  
    listForSetUsing=list(setForUniqueDomain)
    
    for k in (listForSetUsing):  
        f.seek(0)      
        # print(k) is working
        for i in (f):
            
        
            part1=i.split()
            
            domen=part1[2].split(":")
            
            if (k == domen[0]):
                counterForThirdQuestion[yeniqounter]+=1   
            
                
        yeniqounter+=1
    f.seek(0)
    for i in (f):
        part1=i.split()
        domen=part1[2].split(":")
        if (listForSetUsing[counterForThirdQuestion.index(min(counterForThirdQuestion))] == domen[0]):
            asnwerForThirdQuestion=part1[5]
            break
        
         
        
        
    # print(counterForThirdQuestion) 
    # print(min(counterForThirdQuestion))
    # print(listForSetUsing[counterForThirdQuestion.index(min(counterForThirdQuestion))])
                
# part 4:        
    #write here  
           
    setForTaskFour= set()
    f.seek(0)
    
    
    for i in (f):
         part1=i.split()
         domen=part1[2].split(":")  
         damen=domen[0].split(".")
         if(damen[len(damen)-1] == "thm"):
             setForTaskFour.add(domen[0])
    # print(setForTaskFour)
    f.seek(0)
    caunterTaskFour=0
    couterTaskFour=[0] * len(setForTaskFour) 
    listForTaskFour=list(setForTaskFour)
    for fff in (setForTaskFour):
        f.seek(0)
        for i in (f):
            part1=i.split()
            domen=part1[2].split(":")
            if(domen[0]==fff):
                couterTaskFour[caunterTaskFour]+=1
        caunterTaskFour+=1
        
    asnwerForFourthQuestion=listForTaskFour[couterTaskFour.index(max(couterTaskFour))]
    # print(listForTaskFour)
    # print(couterTaskFour.index(max(couterTaskFour)))
    # print(max(couterTaskFour))
    # print(couterTaskFour)
    
    
# task 5
    #write here
    setForTaskFive= set()
    f.seek(0)
    for i in (f):
        parrt1=i.split()
        omen=parrt1[2].split(":")
        amen=omen[0].split(".")
        if(amen[len(amen)-1] == "thm"):
             setForTaskFive.add(parrt1[1])

    
    
    
    print(f"1.How many unique IP addresses are connected to the proxy server? --> {counterUniqueIp}")
    print(f"2. How many unique domains were accessed by all workstations? --> {len(setForUniqueDomain)}")
    print(f"3. What status code is generated by the HTTP requests to the least accessed domain? --> {asnwerForThirdQuestion}")
    print(f"4. Based on the high count of connection attempts, what is the name of the suspicious domain? --> {asnwerForFourthQuestion}")            
    print("5. What is the source IP of the workstation that accessed the malicious domain? -->", *setForTaskFive)
except Exception as e:
    print("Problem Occured:")
    print(e)
        

